### ISSUE TITLE
Remove passwords from yaml definition

### ISSUE THREAD

**Issue by jan-schutte** [NoxOrg/Nox.Generator#129]
- remove the secrets (database passwords) from the sample yaml definition sections and rather refer to environment variables
- use the environment variable values in solution yaml definition
- allow for user secrets in solution yaml
Sample yaml definition
```yaml
variables:
  DATABASE_PASSWORD: ${{ user.secrets.databasePassword }}

infrastructure:
  
  persistence:

    databaseServer:
      name: SampleCurrencyDb

      # Sql Server
      serverUri: localhost
      provider: sqlServer
      port: 1433
      user: sa
      password: ${{ env.DATABASE_PASSWORD }}
      options: Trusted_Connection=no;connection timeout=120;TrustServerCertificate=True;
```
