### ISSUE TITLE
Nox.Solution: Override environment variables with variables in envrironment section

### ISSUE THREAD

**Issue by jan-schutte** [NoxOrg/Nox.Generator#164]
- override any environment variables with the values defined in the variables section of the yaml definition
```yaml
variables:
  DATABASE_PROVIDER: slqServer
  DATABASE_SERVER: localhost
  DATABASE_USER: sa
  DATABASE_PASSWORD: Developer*123
  DATABASE_PORT: "5432"
```
example: anywhere in the yaml definition where ${{ env.DATABASE_PROVIDER }} exists, it must be replaced by sqlserver
