### ISSUE TITLE
[Nox.Ui] Cryptocash.Ui Implement Infrastructure.Security.ApplicationIdentity config settings

### ISSUE THREAD

**Issue by DanielHodgeGH** [NoxOrg/Nox.Generator#581]
as agreed in 16/Aug/23 meeting ad config for the following:

AzureAuth = Infrastructure.Security.ApplicationIdentity

```yaml
infrastructure:
  security:
    userIdentity:
      provider: AzureAd 
      azureAdOptions:
        instance: https://login.microsoftonline.com
        domain: xxx
        tenantId: xxx (vault secret)
        clientId: xxx (vault secret)
        callBackPath: /signin-oidc
        signedOutCallBackPath: /signout-callback-oidc
```
  
job1: update Nox.Solution support & validate settings - see NoxSimpleTypeDefinition = expects instance, domain etc - validation
