### ISSUE TITLE
Create a generator for Domain events

### ISSUE THREAD

**Issue by jan-schutte** [NoxOrg/Nox.Generator#8]
Create concrete classes for all the domain events in a nox solution
yaml definition:
```yaml
      events:
        - name: CountryNameUpdatedEvent
          description: Raised when the name of a country changes
          type: object
          objectTypeOptions:
            attributes:
              
              - name: CountryId
                description: The identifier of the country. The Iso alpha 2 code
                type: countryCode2
              
              - name: CountryName
                description: The new name of the country
                type: text   
```
Generated class:
```C#
// Generated by DomainEventGenerator::Generate

using Nox.Core.Interfaces.Entity;
using Nox.Types;
using System.Collections.Generic;

namespace SampleService.Domain;

/// <summary>
/// a Domain event which is raised when the name of a country changes
/// </summary>
public partial class CountryNameUpdatedEvent : INoxEvent
{

    /// <summary>
    /// The identity of the country, the Iso Alpha 2 code.
    /// </summary>
    public CountryCode2? CountryId { get; set; } = null!;

    /// <summary>
    /// The new name of the country
    /// </summary>
    public Text? CountryName { get; set; } = null!;
}
```
